# 無効にするルール
disabled_rules:
- trailing_whitespace  # 余分に改行がある方が視認性が上がる為、無効
- type_name            # クラス名は長くして情報を詰めておく必要もある為、無効

# Lint対象から外すファイルのあるパスを記述
excluded:
- Pods
- Carthage
- _frameworks

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly

# 一行の文字列制限
line_length: 300

# or they can set both explicitly
file_length:
  warning: 800
  error: 1200

# クラスの行数
type_body_length:
- 300  # warning
- 400  # error

# 変数名の最大文字数
variable_name_max_length:
- 60  # warning
- 80  # error

# 変数名の最小文字数
variable_name_min_length:
- 1  # warning
- 0  # error

variable_name:
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

# 関数の長さ
function_body_length:
- 100  # warning
- 200  # error
